### ISSUE TITLE
Shared Branch

### ISSUE THREAD

**Issue by mikshepard** [brantje/nextnote#45]
I'm curious on the status of the Shared branch?  I've been using it and for the most part, seems to be working fine.  Only thing I've seen so far is the shared names (when a note is shared with you) overlays on the edit button.  The shared feature is a huge step forward and I love it.  Is there plans to continue this branch?

**Comment by ThomasDaheim** [comment]
I strongly hope so. Its only that @brantje has been silent lately :-(

**Comment by brantje** [comment]
I have a lack of testers, so thanks that you would let me know that it works.

**Comment by mikshepard** [comment]
@brantje, Sure, I'm running in a test environment with a few users.  I'm happy to report an issues and apply any commits you'd like me to try.

Again, so far, so good.  No real issues on my end but I'll start watching more closely for them and reporting.  Thanks again

**Comment by tinylcy** [comment]
Hi @mikshepard ,

I have some problems when using sharing branch, can you tell me the version of your NextCloud? 
Thx~

**Comment by mikshepard** [comment]
Sure, I'm running the following:

Nextcloud 12.0.3 (soon to be 12.0.4 later this week) w/LDAP Auth
OS Debian Jessie
php 5.6.30
mysql 5.7.20
apache 2.4.10

What issues are you having?

**Comment by tinylcy** [comment]
Hi @mikshepard , thanks for your quick response.
 
The following are my problems I have met yesterday, maybe you can give me some useful advice.

I use NextCloud 12.0.3, and the branch of NextNote is the **sharing** branch.
When I create a note in NextNote and then click the **Share Note** button, overlays occurred but this is not a big problem.

![image](https://user-images.githubusercontent.com/11954488/33971728-fb982144-e0b4-11e7-8729-f01e70d693cd.png)

But when I enter an user name or a group name, NextNote shows me some errors.

![image](https://user-images.githubusercontent.com/11954488/33971805-4dbd1fe2-e0b5-11e7-89ef-b07bf660444b.png)

I'm sorry that I'm not familiar with PHP, so it would be great if you could give me some help :) .
 
-------

I have fixed the bug and the reason is absolute path problem, and I have modified the code of `./js/share.js:361`.

```
$.get('/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=' + search.term.trim() + '&perPage=200&itemType=' + itemType, {
    fetch: 'getShareWith',
    search: search.term.trim(),
    perPage: 200,
    itemShares: this.itemShares,
    itemType: itemType
}
```

**Comment by mikshepard** [comment]
I've tried to recreate the problem you are experiencing but I'm not getting those errors.  When sharing a note and typing in the name, nothing appears in the console like that.  I am using LDAP for my users although, not local ones.

What path did you change that to, btw?  I'm curious.

**Comment by brantje** [comment]
Renamed `sharing` to `sharing-deprecated` since most methods are deprecated / moved in NC14.
Was thinking about updating the sharing branch to work with NC14 / NC13. But i think the Nextcloud team burried those docs deep, aside of all other dev docs. So due the lack of documentation i will stop working on the sharing branch.
